title:            Simple-Concise
description:      A framework-tool-whadayaknow that helps developing new applications/systems hoping to minimize repetition while allowing to fulfill my specialized non functional requirements
url: http://mtzmontiel.github.io/simple-concise

owner:
  name:           Rafael Martinez Montiel

timezone:    America/Mexico_City
