title:            Simple-Concise
description:      A framework-tool-whadayaknow that helps developing new applications/systems hoping to minimize repetition while allowing to fulfill my specialized non functional requirements

owner:
  name:           Rafael Martinez Montiel
