// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mx.rmm.simpleconcise.roomvc.model;

import mx.rmm.simpleconcise.roomvc.model.Artifact;

privileged aspect Artifact_Roo_JavaBean {
    
    public String Artifact.getName() {
        return this.name;
    }
    
    public void Artifact.setName(String name) {
        this.name = name;
    }
    
}
