// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mx.rmm.simpleconcise.roomvc.model;

import mx.rmm.simpleconcise.roomvc.model.Server;

privileged aspect Server_Roo_JavaBean {
    
    public String Server.getName() {
        return this.name;
    }
    
    public void Server.setName(String name) {
        this.name = name;
    }
    
}
