// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mx.rmm.simpleconcise.roo.web.converter;

import mx.rmm.simpleconcise.roo.web.converter.ItemConverter;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ItemConverter_Roo_Configurable {
    
    declare @type: ItemConverter: @Configurable;
    
}
