// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mx.rmm.simpleconcise.roomvc.model;

import mx.rmm.simpleconcise.roomvc.model.ArtifactDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ArtifactDataOnDemand_Roo_Configurable {
    
    declare @type: ArtifactDataOnDemand: @Configurable;
    
}
