// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mx.rmm.simpleconcise.roomvc.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import mx.rmm.simpleconcise.roomvc.model.Catalogue;
import mx.rmm.simpleconcise.roomvc.model.CatalogueDataOnDemand;
import mx.rmm.simpleconcise.roomvc.model.CatalogueStatus;
import org.springframework.stereotype.Component;

privileged aspect CatalogueDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CatalogueDataOnDemand: @Component;
    
    private Random CatalogueDataOnDemand.rnd = new SecureRandom();
    
    private List<Catalogue> CatalogueDataOnDemand.data;
    
    public Catalogue CatalogueDataOnDemand.getNewTransientCatalogue(int index) {
        Catalogue obj = new Catalogue();
        setCode(obj, index);
        setDescription(obj, index);
        setStatus(obj, index);
        return obj;
    }
    
    public void CatalogueDataOnDemand.setCode(Catalogue obj, int index) {
        String code = "code_" + index;
        obj.setCode(code);
    }
    
    public void CatalogueDataOnDemand.setDescription(Catalogue obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void CatalogueDataOnDemand.setStatus(Catalogue obj, int index) {
        CatalogueStatus status = CatalogueStatus.class.getEnumConstants()[0];
        obj.setStatus(status);
    }
    
    public Catalogue CatalogueDataOnDemand.getSpecificCatalogue(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Catalogue obj = data.get(index);
        Long id = obj.getId();
        return Catalogue.findCatalogue(id);
    }
    
    public Catalogue CatalogueDataOnDemand.getRandomCatalogue() {
        init();
        Catalogue obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Catalogue.findCatalogue(id);
    }
    
    public boolean CatalogueDataOnDemand.modifyCatalogue(Catalogue obj) {
        return false;
    }
    
    public void CatalogueDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Catalogue.findCatalogueEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Catalogue' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Catalogue>();
        for (int i = 0; i < 10; i++) {
            Catalogue obj = getNewTransientCatalogue(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
