// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mx.rmm.simpleconcise.roomvc.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import mx.rmm.simpleconcise.roomvc.model.Container;
import mx.rmm.simpleconcise.roomvc.model.ContainerDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect ContainerDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ContainerDataOnDemand: @Component;
    
    private Random ContainerDataOnDemand.rnd = new SecureRandom();
    
    private List<Container> ContainerDataOnDemand.data;
    
    public Container ContainerDataOnDemand.getNewTransientContainer(int index) {
        Container obj = new Container();
        setCode(obj, index);
        setDescription(obj, index);
        return obj;
    }
    
    public void ContainerDataOnDemand.setCode(Container obj, int index) {
        String code = "code_" + index;
        obj.setCode(code);
    }
    
    public void ContainerDataOnDemand.setDescription(Container obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public Container ContainerDataOnDemand.getSpecificContainer(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Container obj = data.get(index);
        Long id = obj.getId();
        return Container.findContainer(id);
    }
    
    public Container ContainerDataOnDemand.getRandomContainer() {
        init();
        Container obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Container.findContainer(id);
    }
    
    public boolean ContainerDataOnDemand.modifyContainer(Container obj) {
        return false;
    }
    
    public void ContainerDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Container.findContainerEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Container' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Container>();
        for (int i = 0; i < 10; i++) {
            Container obj = getNewTransientContainer(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
