// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mx.rmm.simpleconcise.roo.web;

import mx.rmm.simpleconcise.roo.web.ArtifactBean;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ArtifactBean_Roo_Configurable {
    
    declare @type: ArtifactBean: @Configurable;
    
}
