// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mx.rmm.simpleconcise.roo.web;

import java.io.Serializable;
import mx.rmm.simpleconcise.roo.web.ContainerBean;

privileged aspect ContainerBean_Roo_Serializable {
    
    declare parents: ContainerBean implements Serializable;
    
    private static final long ContainerBean.serialVersionUID = 1L;
    
}
