// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mx.rmm.simpleconcise.roo.web;

import java.io.Serializable;
import mx.rmm.simpleconcise.roo.web.DeploymentBean;

privileged aspect DeploymentBean_Roo_Serializable {
    
    declare parents: DeploymentBean implements Serializable;
    
    private static final long DeploymentBean.serialVersionUID = 1L;
    
}
