// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mx.rmm.simpleconcise.roo.web;

import java.io.Serializable;
import mx.rmm.simpleconcise.roo.web.ServerBean;

privileged aspect ServerBean_Roo_Serializable {
    
    declare parents: ServerBean implements Serializable;
    
    private static final long ServerBean.serialVersionUID = 1L;
    
}
