// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mx.rmm.simpleconcise.roo.model;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import mx.rmm.simpleconcise.roo.model.Catalogue;
import mx.rmm.simpleconcise.roo.model.CatalogueDataOnDemand;
import mx.rmm.simpleconcise.roo.model.CatalogueIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CatalogueIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CatalogueIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CatalogueIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CatalogueIntegrationTest: @Transactional;
    
    @Autowired
    CatalogueDataOnDemand CatalogueIntegrationTest.dod;
    
    @Test
    public void CatalogueIntegrationTest.testCountCatalogues() {
        Assert.assertNotNull("Data on demand for 'Catalogue' failed to initialize correctly", dod.getRandomCatalogue());
        long count = Catalogue.countCatalogues();
        Assert.assertTrue("Counter for 'Catalogue' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CatalogueIntegrationTest.testFindCatalogue() {
        Catalogue obj = dod.getRandomCatalogue();
        Assert.assertNotNull("Data on demand for 'Catalogue' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Catalogue' failed to provide an identifier", id);
        obj = Catalogue.findCatalogue(id);
        Assert.assertNotNull("Find method for 'Catalogue' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Catalogue' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CatalogueIntegrationTest.testFindAllCatalogues() {
        Assert.assertNotNull("Data on demand for 'Catalogue' failed to initialize correctly", dod.getRandomCatalogue());
        long count = Catalogue.countCatalogues();
        Assert.assertTrue("Too expensive to perform a find all test for 'Catalogue', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Catalogue> result = Catalogue.findAllCatalogues();
        Assert.assertNotNull("Find all method for 'Catalogue' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Catalogue' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CatalogueIntegrationTest.testFindCatalogueEntries() {
        Assert.assertNotNull("Data on demand for 'Catalogue' failed to initialize correctly", dod.getRandomCatalogue());
        long count = Catalogue.countCatalogues();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Catalogue> result = Catalogue.findCatalogueEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Catalogue' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Catalogue' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CatalogueIntegrationTest.testFlush() {
        Catalogue obj = dod.getRandomCatalogue();
        Assert.assertNotNull("Data on demand for 'Catalogue' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Catalogue' failed to provide an identifier", id);
        obj = Catalogue.findCatalogue(id);
        Assert.assertNotNull("Find method for 'Catalogue' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCatalogue(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Catalogue' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CatalogueIntegrationTest.testMergeUpdate() {
        Catalogue obj = dod.getRandomCatalogue();
        Assert.assertNotNull("Data on demand for 'Catalogue' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Catalogue' failed to provide an identifier", id);
        obj = Catalogue.findCatalogue(id);
        boolean modified =  dod.modifyCatalogue(obj);
        Integer currentVersion = obj.getVersion();
        Catalogue merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Catalogue' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CatalogueIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Catalogue' failed to initialize correctly", dod.getRandomCatalogue());
        Catalogue obj = dod.getNewTransientCatalogue(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Catalogue' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Catalogue' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Catalogue' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CatalogueIntegrationTest.testRemove() {
        Catalogue obj = dod.getRandomCatalogue();
        Assert.assertNotNull("Data on demand for 'Catalogue' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Catalogue' failed to provide an identifier", id);
        obj = Catalogue.findCatalogue(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Catalogue' with identifier '" + id + "'", Catalogue.findCatalogue(id));
    }
    
}
