// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package mx.rmm.simpleconcise.roo.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import mx.rmm.simpleconcise.roo.model.Artifact;
import mx.rmm.simpleconcise.roo.model.ArtifactDataOnDemand;
import mx.rmm.simpleconcise.roo.model.Deployment;
import mx.rmm.simpleconcise.roo.model.DeploymentDataOnDemand;
import mx.rmm.simpleconcise.roo.model.DeploymentStatus;
import mx.rmm.simpleconcise.roo.model.Server;
import mx.rmm.simpleconcise.roo.model.ServerDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect DeploymentDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DeploymentDataOnDemand: @Component;
    
    private Random DeploymentDataOnDemand.rnd = new SecureRandom();
    
    private List<Deployment> DeploymentDataOnDemand.data;
    
    @Autowired
    ArtifactDataOnDemand DeploymentDataOnDemand.artifactDataOnDemand;
    
    @Autowired
    ServerDataOnDemand DeploymentDataOnDemand.serverDataOnDemand;
    
    public Deployment DeploymentDataOnDemand.getNewTransientDeployment(int index) {
        Deployment obj = new Deployment();
        setArtifact(obj, index);
        setName(obj, index);
        setSchedulledDate(obj, index);
        setServer(obj, index);
        setStatus(obj, index);
        return obj;
    }
    
    public void DeploymentDataOnDemand.setArtifact(Deployment obj, int index) {
        Artifact artifact = artifactDataOnDemand.getRandomArtifact();
        obj.setArtifact(artifact);
    }
    
    public void DeploymentDataOnDemand.setName(Deployment obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void DeploymentDataOnDemand.setSchedulledDate(Deployment obj, int index) {
        Date schedulledDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setSchedulledDate(schedulledDate);
    }
    
    public void DeploymentDataOnDemand.setServer(Deployment obj, int index) {
        Server server = serverDataOnDemand.getRandomServer();
        obj.setServer(server);
    }
    
    public void DeploymentDataOnDemand.setStatus(Deployment obj, int index) {
        DeploymentStatus status = DeploymentStatus.class.getEnumConstants()[0];
        obj.setStatus(status);
    }
    
    public Deployment DeploymentDataOnDemand.getSpecificDeployment(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Deployment obj = data.get(index);
        Long id = obj.getId();
        return Deployment.findDeployment(id);
    }
    
    public Deployment DeploymentDataOnDemand.getRandomDeployment() {
        init();
        Deployment obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Deployment.findDeployment(id);
    }
    
    public boolean DeploymentDataOnDemand.modifyDeployment(Deployment obj) {
        return false;
    }
    
    public void DeploymentDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Deployment.findDeploymentEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Deployment' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Deployment>();
        for (int i = 0; i < 10; i++) {
            Deployment obj = getNewTransientDeployment(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
